name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Validation test
      id: validation-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Validation test
        setup-command: npm install
        command: npm test
        timeout: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        VALIDATION-TEST_RESULTS: "${{steps.validation-test.outputs.result}}"
      with:
        runners: validation-test
